apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
    labels:
        app: user-service
        tier: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
                tier: backend
        spec:
            containers:
                - name: user-service
                  image: user-service
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  env:
                      - name: SERVER_PORT
                        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: user-service
    name: user-service-service
spec:
    ports:
        - port: 90
          targetPort: 8080
    selector:
        app: user-service