server:
  port: 8081

spring:
  application:
    name: 'user-service'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
SECRET_KEY: ${SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"