server:
  port: 8081

spring:
  application:
    name: 'user-service'
  datasource:
#    url: jdbc:postgresql://34.130.185.111:5432/demo
#    username: jason-yeung
#    password: Ccc12345
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
SECRET_KEY: ${SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"