apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: user-service
          image: user-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "1000Mi"
              cpu: "200m"
          ports:
            - containerPort: 8081
          envFrom:
          - configMapRef:
              name: user-service-config
          - secretRef:
              name: user-service-secrets
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 90
      targetPort: 8081
  selector:
    app: user-service
